[package]
name = "oxidfetch"
version = "0.1.0"
edition = "2018"

[dependencies]
anyhow = "1.0.44"
rmp-serde = "0.15.5"
serde = "1.0.130"
serde_derive = "1.0.130"
ansi_term = "0.12.1"
regex = "1.5.4"
whoami = "1.1.3"

[dependencies.mlua]
version = "0.6.3"
features = ["vendored", "luajit"]
